#!/bin/bash

set -e

if [ ! -f key ] ; then
   echo "Generating"
   openssl genrsa -out key.pem 2048
   ssh-keygen -y -f key.pem > key.pub
   #ssh-keygen -b 2048 -t rsa -f key.pem -q -N "" -m PEM
   chmod 400 key*
else
   echo "Key alreay found, skipping generation"
fi

echo "Init success"

