#!/bin/bash

set -e

if [ ! -f key ] ; then
   echo "Generating"
   
   ssh-keygen -P "" -m PEM -f key
   #ssh-keygen -b 2048 -t rsa -f key.pem -q -N "" -m PEM
   chmod 400 key
   chmod 400 key.pub
else
   echo "Key already found, skipping generation"
fi

echo "Init success"

